# filename: config.toml
title="Hello.."

[DATABASE]
HOST = "localhost"
PORT = "3306"
NAME_DB = "manfaat2"
USER = "root"
PASSWORD = "uSS10nl1n3"

[DATABASE_SYS]
HOST = "localhost"
PORT = "3306"
NAME_DB = "manfaat2_sys"
USER = "root"
PASSWORD = "uSS10nl1n3"

[SET_ID]
KEYNAME_NASABAH_ID = "CSS_TEMPLATE_NASABAH_ID"
KEYNAME_NOREK = "TAB_TEMPLATE_NO_REKENING"

[VAR_REGAGTBYAGEN]
BIAYA_PENDAFTARAN = 35000.00
BIAYA_FEE_ADM = 20000.00
BIAYA_FEE_AGEN = 10000.00
BIAYA_DAFTAR_AGEN = 500000.00

[POINT_TRANS]
POINT_TRANS_PULSA = 10
POINT_REG_AGT_BYAGENT = 20
POINT_REK_BERJANGKA_UMROH = 20

[FEE_PAY_PULSA]
FEE_USER = 60
FEE_LKM = 20
FEE_AGEN_USER = 20

[PERKIRAAN]
SUKARELA_LKM = "20201"
DEPOSIT_ECHANNEL = "10406"
PENDAPATAN_NON_OPERASIONAL = "40205"

[server]
port = "8080"